In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/everydaycodings/multi-platform-online-courses-dataset/edx.csv
/kaggle/input/datasets/everydaycodings/multi-platform-online-courses-dataset/skillshare.csv
/kaggle/input/datasets/everydaycodings/multi-platform-online-courses-dataset/Udemy.csv
/kaggle/input/datasets/everydaycodings/multi-platform-online-courses-dataset/Coursera.csv

In [2]:
df_udemy = pd.read_csv("/kaggle/input/datasets/everydaycodings/multi-platform-online-courses-dataset/Udemy.csv")
df_coursera = pd.read_csv("/kaggle/input/datasets/everydaycodings/multi-platform-online-courses-dataset/Coursera.csv")

In [3]:
df_udemy.shape

(26256, 8)

In [4]:
df_coursera.shape

(1139, 9)

In [5]:
# This makes every ID exactly 5 digits long (e.g., c00001, c26256)
df_udemy['Course_Id'] = [f'u{i:05d}' for i in range(1, len(df_udemy) + 1)]
df_coursera['Course_Id'] = [f'c{i:04d}' for i in range(1, len(df_coursera) + 1)]

In [6]:
df_udemy.head()

,title,description,instructor,rating,reviewcount,duration,lectures,level,Course_Id
0,The Complete Python Bootcamp From Zero to Hero...,Learn Python like a Professional Start from t...,Jose Portilla,4.6,486391,22 total hours,156 lectures,All Levels,u00001
1,The Complete 2023 Web Development Bootcamp,Become a Full-Stack Web Developer with just ON...,Dr. Angela Yu,4.7,338555,63 total hours,380 lectures,All Levels,u00002
2,The Web Developer Bootcamp 2023,10 Hours of React just added. Become a Develop...,Colt Steele,4.7,266527,74 total hours,722 lectures,All Levels,u00003
3,100 Days of Code: The Complete Python Pro Boot...,Master Python by building 100 projects in 100 ...,Dr. Angela Yu,4.7,251585,58 total hours,636 lectures,All Levels,u00004
4,React - The Complete Guide 2023 (incl. React R...,Dive in and learn React.js from scratch! Learn...,"Academind by Maximilian Schwarzmüller, Maximil...",4.6,199663,74.5 total hours,739 lectures,All Levels,u00005

In [7]:
df_coursera.head()

,partner,course,skills,rating,reviewcount,level,certificatetype,duration,crediteligibility,Course_Id
0,Google,Google Cybersecurity,"{"" Network Security"","" Python Programming"","" L...",4.8,16.4k,Beginner,Professional Certificate,3 - 6 Months,False,c0001
1,Google,Google Data Analytics,"{"" Data Analysis"","" R Programming"","" SQL"","" Bu...",4.8,133.4k,Beginner,Professional Certificate,3 - 6 Months,True,c0002
2,Google,Google Project Management:,"{"" Project Management"","" Strategy and Operatio...",4.8,97.3k,Beginner,Professional Certificate,3 - 6 Months,True,c0003
3,Google,Google Digital Marketing & E-commerce,"{"" Digital Marketing"","" Marketing"","" Marketing...",4.8,21.4k,Beginner,Professional Certificate,3 - 6 Months,False,c0004
4,Google,Google IT Support,"{"" Computer Networking"","" Network Architecture...",4.8,181.4k,Beginner,Professional Certificate,3 - 6 Months,True,c0005

In [8]:
df_udemy.drop(['instructor','lectures'] , axis=1 , inplace = True)
df_coursera.drop(['partner','certificatetype','crediteligibility'], axis=1 , inplace = True)

In [9]:
df_coursera['description'] = df_coursera['course'] + " " + df_coursera['skills']

In [10]:
df_coursera.drop(['skills'], axis=1 , inplace = True)

In [11]:
df_coursera = df_coursera.rename(columns={'course' : 'course_title'})
df_udemy = df_udemy.rename(columns={'title' : 'course_title'})

In [12]:
df_udemy['level'].isnull().sum()

np.int64(367)

In [13]:
df_coursera['level'].value_counts()

level
Beginner          675
Intermediate      200
Mixed              89
Advanced           36
Course              2
Specialization      1
Degree              1
Name: count, dtype: int64

In [14]:
# Standardizing Dataset 1
df_udemy['level'] = df_udemy['level'].replace({
    'Expert': 'Advanced'
})

# Standardizing Dataset 2
df_coursera['level'] = df_coursera['level'].replace({
    'Mixed ': 'All Levels',
    'Intermediate ': 'Intermediate',
    'Advanced ': 'Advanced',
    'Beginner ': 'Beginner',
    'Specialization': 'Advanced',
    'Degree': 'Advanced',
    'Course': 'Beginner' # Or drop these if they aren't relevant
})

In [15]:
df_coursera['level'] = df_coursera['level'].fillna('Beginner')

In [16]:
df_udemy['level'].value_counts()

level
All Levels      14776
Beginner         7471
Intermediate     3195
Advanced          447
Name: count, dtype: int64

In [17]:
df_udemy.dropna(subset=['description'], inplace=True)

In [18]:
df_udemy['level'] = df_udemy['level'].fillna('All Levels')

In [19]:
df_udemy.isnull().sum()

course_title    0
description     0
rating          0
reviewcount     0
duration        0
level           0
Course_Id       0
dtype: int64

In [20]:
df_udemy.head()

,course_title,description,rating,reviewcount,duration,level,Course_Id
0,The Complete Python Bootcamp From Zero to Hero...,Learn Python like a Professional Start from t...,4.6,486391,22 total hours,All Levels,u00001
1,The Complete 2023 Web Development Bootcamp,Become a Full-Stack Web Developer with just ON...,4.7,338555,63 total hours,All Levels,u00002
2,The Web Developer Bootcamp 2023,10 Hours of React just added. Become a Develop...,4.7,266527,74 total hours,All Levels,u00003
3,100 Days of Code: The Complete Python Pro Boot...,Master Python by building 100 projects in 100 ...,4.7,251585,58 total hours,All Levels,u00004
4,React - The Complete Guide 2023 (incl. React R...,Dive in and learn React.js from scratch! Learn...,4.6,199663,74.5 total hours,All Levels,u00005

In [21]:
# 1. Remove rows where duration mentions 'questions'
df_udemy = df_udemy[~df_udemy['duration'].str.contains('questions', case=False, na=False)]

# 2. Remove rows where 'All Levels' accidentally leaked into duration
df_udemy = df_udemy[~df_udemy['duration'].str.contains('All Levels', case=False, na=False)]

print(f"Rows remaining in Udemy after filtering: {len(df_udemy)}")

Rows remaining in Udemy after filtering: 25889

In [22]:
df_udemy['duration'].value_counts()

duration
2 total hours        2089
1.5 total hours      2006
1 total hour         1960
2.5 total hours      1715
3 total hours        1583
                     ...
90.5 total hours        1
109 total hours         1
120 total hours         1
152.5 total hours       1
146.5 total hours       1
Name: count, Length: 243, dtype: int64

In [23]:
# Regex breakdown:
# (\d+\.?\d*) -> Captures the number (including decimals like 74.5)
# \s+          -> Matches the space
# (.*)         -> Captures everything after the space (the unit)

df_udemy[['duration_val', 'duration_unit']] = df_udemy['duration'].str.extract(r'(\d+\.?\d*)\s+(.*)')

# Convert the value column to a float so you can do math
df_udemy['duration_val'] = df_udemy['duration_val'].astype(float)

In [24]:
print(df_udemy['duration_unit'].value_counts())

duration_unit
total hours    23185
total hour      1960
total mins       744
Name: count, dtype: int64

In [25]:
# 1. Convert the numerical value for 'total mins'
df_udemy.loc[df_udemy['duration_unit'] == 'total mins', 'duration_val'] = df_udemy['duration_val'] / 60

# 2. Standardize the unit name to 'hour' for everything
df_udemy['duration_unit'] = 'hour'

# 3. Rename the column to be descriptive
df_udemy.rename(columns={'duration_val': 'duration_hours'}, inplace=True)

In [26]:
df_udemy.columns

Index(['course_title', 'description', 'rating', 'reviewcount', 'duration',
       'level', 'Course_Id', 'duration_hours', 'duration_unit'],
      dtype='object')

In [27]:
df_udemy.drop(['duration_unit','duration'] , axis=1 , inplace = True)

In [28]:
df_udemy.head()

,course_title,description,rating,reviewcount,level,Course_Id,duration_hours
0,The Complete Python Bootcamp From Zero to Hero...,Learn Python like a Professional Start from t...,4.6,486391,All Levels,u00001,22.0
1,The Complete 2023 Web Development Bootcamp,Become a Full-Stack Web Developer with just ON...,4.7,338555,All Levels,u00002,63.0
2,The Web Developer Bootcamp 2023,10 Hours of React just added. Become a Develop...,4.7,266527,All Levels,u00003,74.0
3,100 Days of Code: The Complete Python Pro Boot...,Master Python by building 100 projects in 100 ...,4.7,251585,All Levels,u00004,58.0
4,React - The Complete Guide 2023 (incl. React R...,Dive in and learn React.js from scratch! Learn...,4.6,199663,All Levels,u00005,74.5

In [29]:
df_udemy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25889 entries, 0 to 26255
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   course_title    25889 non-null  object
 1   description     25889 non-null  object
 2   rating          25889 non-null  float64
 3   reviewcount     25889 non-null  int64
 4   level           25889 non-null  object
 5   Course_Id       25889 non-null  object
 6   duration_hours  25889 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 2.6+ MB

In [30]:
df_coursera.head()

,course_title,rating,reviewcount,level,duration,Course_Id,description
0,Google Cybersecurity,4.8,16.4k,Beginner,3 - 6 Months,c0001,"Google Cybersecurity {"" Network Security"","" Py..."
1,Google Data Analytics,4.8,133.4k,Beginner,3 - 6 Months,c0002,"Google Data Analytics {"" Data Analysis"","" R Pr..."
2,Google Project Management:,4.8,97.3k,Beginner,3 - 6 Months,c0003,"Google Project Management: {"" Project Manageme..."
3,Google Digital Marketing & E-commerce,4.8,21.4k,Beginner,3 - 6 Months,c0004,"Google Digital Marketing & E-commerce {"" Digit..."
4,Google IT Support,4.8,181.4k,Beginner,3 - 6 Months,c0005,"Google IT Support {"" Computer Networking"","" Ne..."

In [31]:
df_coursera.isnull().sum()

course_title      0
rating          146
reviewcount     146
level             0
duration         23
Course_Id         0
description      51
dtype: int64

In [32]:
def convert_k_to_num(val):
    if pd.isna(val):
        return 0  # Or np.nan if you prefer to handle nulls later
    
    val = str(val).lower().strip()
    
    if 'k' in val:
        # Remove 'k' and multiply by 1000
        return float(val.replace('k', '')) * 1000
    else:
        # Just convert the existing string number to float
        return int(val)

# Apply to your column
df_coursera['reviewcount'] = df_coursera['reviewcount'].apply(convert_k_to_num)

# Verify the result
print(df_coursera['reviewcount'].head())

0     16400.0
1    133400.0
2     97300.0
3     21400.0
4    181400.0
Name: reviewcount, dtype: float64

In [33]:
df_coursera['rating'] = df_coursera['rating'].fillna(0)

In [34]:
df_coursera['duration'].value_counts()

duration
3 - 6 Months                                                   451
1 - 3 Months                                                   333
1 - 4 Weeks                                                    207
6 - 12 Months                                                   40
1 - 4 Years                                                     21
Less Than 2 Hours                                                9
4 meses                                                          8
24 meses                                                         5
24 months                                                        4
6 meses                                                          4
2 years                                                          3
3 – 6 years                                                      3
4 months                                                         2
24 - 36 months                                                   2
1 – 3 years                                                      2
24 meses.                                                        2
24 - 60 months                                                   1
4 months to complete                                             1
26 meses                                                         1
4-6 months to complete                                           1
15+ hours of study/wk per course                                 1
6-7 months to complete                                           1
16 – 60 months                                                   1
12 months                                                        1
24 to 60 months                                                  1
1 year                                                           1
4 years                                                          1
18-24 Months                                                     1
2 to 4 years depending on beginning credits and course load      1
3- 6 years                                                       1
1.5 – 3 years                                                    1
4-8 years                                                        1
2 – 3 years                                                      1
2 or 3 years                                                     1
 24 - 36 months                                                  1
18 a 24 meses                                                    1
Name: count, dtype: int64

In [35]:
import pandas as pd
import re
import numpy as np

def standardize_to_months(text):
    if pd.isna(text): return np.nan
    text = str(text).lower()
    
    # 1. Standardize synonyms and languages
    text = text.replace('meses', 'months').replace('mes', 'month').replace('a', '-')
    
    # 2. Extract all numbers (handles decimals and ranges)
    nums = [float(n) for n in re.findall(r"[-+]?\d*\.\d+|\d+", text)]
    if not nums: return np.nan
    
    # 3. Get the average if it's a range (e.g., 3-6 becomes 4.5)
    val = sum(nums) / len(nums)
    
    # 4. Convert units to months
    if 'year' in text:
        return val * 12
    elif 'week' in text:
        return val / 4.33 # Average weeks in a month
    elif 'hour' in text:
        return (val / 40) # Assuming 40 hours of study = 1 month
    else:
        return val # Already in months

# Apply the function
df_coursera['duration_months'] = df_coursera['duration'].apply(standardize_to_months)

In [36]:
df_coursera['duration_hours'] = df_coursera['duration_months']*60

In [37]:
df_coursera['duration_hours'] .head()

0    270.0
1    270.0
2    270.0
3    270.0
4    270.0
Name: duration_hours, dtype: float64

In [38]:
df_coursera.columns

Index(['course_title', 'rating', 'reviewcount', 'level', 'duration',
       'Course_Id', 'description', 'duration_months', 'duration_hours'],
      dtype='object')

In [39]:
df_coursera.drop(['duration_months','duration'] , axis=1 , inplace = True)

In [40]:
df_coursera.isnull().sum()

course_title       0
rating             0
reviewcount        0
level              0
Course_Id          0
description       51
duration_hours    23
dtype: int64

In [41]:
df_coursera['duration_hours'] = df_coursera['duration_hours'].fillna(0)

In [42]:
df_coursera['description'] = df_coursera['description'].fillna(df_coursera['course_title'])

In [43]:
df_coursera.head()

,course_title,rating,reviewcount,level,Course_Id,description,duration_hours
0,Google Cybersecurity,4.8,16400.0,Beginner,c0001,"Google Cybersecurity {"" Network Security"","" Py...",270.0
1,Google Data Analytics,4.8,133400.0,Beginner,c0002,"Google Data Analytics {"" Data Analysis"","" R Pr...",270.0
2,Google Project Management:,4.8,97300.0,Beginner,c0003,"Google Project Management: {"" Project Manageme...",270.0
3,Google Digital Marketing & E-commerce,4.8,21400.0,Beginner,c0004,"Google Digital Marketing & E-commerce {"" Digit...",270.0
4,Google IT Support,4.8,181400.0,Beginner,c0005,"Google IT Support {"" Computer Networking"","" Ne...",270.0

In [44]:
df_coursera.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1139 entries, 0 to 1138
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   course_title    1139 non-null   object
 1   rating          1139 non-null   float64
 2   reviewcount     1139 non-null   float64
 3   level           1139 non-null   object
 4   Course_Id       1139 non-null   object
 5   description     1139 non-null   object
 6   duration_hours  1139 non-null   float64
dtypes: float64(3), object(4)
memory usage: 62.4+ KB

In [45]:
# Stack the datasets on top of each other
df_master = pd.concat([df_coursera, df_udemy], ignore_index=True)

# Final check of the new shape (should be ~27,028 rows)
print(f"Master Dataset Shape: {df_master.shape}")

Master Dataset Shape: (27028, 7)

In [46]:
df_master.head()

,course_title,rating,reviewcount,level,Course_Id,description,duration_hours
0,Google Cybersecurity,4.8,16400.0,Beginner,c0001,"Google Cybersecurity {"" Network Security"","" Py...",270.0
1,Google Data Analytics,4.8,133400.0,Beginner,c0002,"Google Data Analytics {"" Data Analysis"","" R Pr...",270.0
2,Google Project Management:,4.8,97300.0,Beginner,c0003,"Google Project Management: {"" Project Manageme...",270.0
3,Google Digital Marketing & E-commerce,4.8,21400.0,Beginner,c0004,"Google Digital Marketing & E-commerce {"" Digit...",270.0
4,Google IT Support,4.8,181400.0,Beginner,c0005,"Google IT Support {"" Computer Networking"","" Ne...",270.0

In [47]:
# Apply the logic to the master dataset
df_master['platform'] = np.where(df_master['Course_Id'].str.startswith('c'), 'Coursera', 'Udemy')

# Verify the counts
print(df_master['platform'].value_counts())

platform
Udemy       25889
Coursera     1139
Name: count, dtype: int64

In [48]:
df_master['Course_Id'] = range(1, len(df_master) + 1)

In [49]:
df_master.tail()

,course_title,rating,reviewcount,level,Course_Id,description,duration_hours,platform
27023,Business English for Meetings,4.6,1015.0,Intermediate,27024,Useful English Phrases for Communicating with ...,1.5,Udemy
27024,Aerospace Engineering: Aircraft Systems and Av...,4.4,1001.0,All Levels,27025,Aerospace and Aeronautical Engineering: Master...,2.5,Udemy
27025,Forensic Psychology : Criminal Profiling Certi...,4.4,1002.0,Beginner,27026,Criminology Crash Course,3.0,Udemy
27026,Deutsch Intensiv - Intensive German Course for...,4.8,996.0,Beginner,27027,Master all the ins and outs of the German lang...,10.5,Udemy
27027,Renewable Energy and Sustainable Development,4.2,995.0,Beginner,27028,Environmental Issues,2.0,Udemy

In [50]:
# Shuffle the entire dataset
# frac=1 means take a 100% sample (reorder everything)
# random_state ensures your results are reproducible (important for interviews!)
df_master = df_master.sample(frac=1, random_state=42).reset_index(drop=True)

# Verify the shuffle
(df_master.tail(10)) 
# You should now see a mix of 'Coursera' and 'Udemy' in the first 10 rows

,course_title,rating,reviewcount,level,Course_Id,description,duration_hours,platform
27018,Fundraising 101,4.2,39.0,Beginner,16851,"An overview for board members and ""accidental""...",1.0,Udemy
27019,Create Board and Video Game Design Projects - ...,4.5,144.0,Beginner,6266,Start designing your own Games (Videogame or B...,9.5,Udemy
27020,Debugging SAP ABAP Code For Non Programmers,4.4,1150.0,All Levels,22119,Quickly learn core SAP commands and ABAP debug...,5.5,Udemy
27021,"Leadership, Business Process Improvement, & Pr...",4.5,3261.0,All Levels,11285,"Learn the leadership, communication, and proce...",3.5,Udemy
27022,Voice Training: Discover Your Confident and Po...,4.6,829.0,All Levels,11965,The Complete Voice Training Course to More Con...,2.0,Udemy
27023,ISO 21434 Automotive Cybersecurity Standards,3.8,358.0,All Levels,21576,"ISO21434, TARA, Security Concept, Stakeholder ...",2.0,Udemy
27024,"Unity 2020, Android Game Development: Create a...",4.4,204.0,Beginner,5391,Master the fundamentals of mobile game develop...,14.0,Udemy
27025,Computational Neuroscience,4.6,1000.0,Beginner,861,"Computational Neuroscience {"" Mathematics"","" C...",120.0,Coursera
27026,"Credit Policy, Products, Delivery, Appraisal, ...",4.9,114.0,All Levels,15796,Guide to Certified Credit Professional Course ...,4.5,Udemy
27027,Change Management Mastery : A Model for Leader...,4.5,2219.0,All Levels,23655,"Learn from the Research, and become a Master o...",3.0,Udemy

In [51]:
# Save to a CSV for your portfolio/project
df_master.to_csv('online_courses_cleaned.csv', index=False)